/* You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t. */

class Solution {
    public char findTheDifference(String s, String t) {
        char[] sAlphabet = new char[26]; 
        char[] tAlphabet = new char[26]; 
        for (int i = 0; i < s.length(); i++) {
            sAlphabet[s.charAt(i) - 97]++;
        }
        for (int i = 0; i < t.length(); i++) {
            tAlphabet[t.charAt(i) - 97]++;
        }
        for (int i = 0; i < 26; i++) {
            if (sAlphabet[i] != tAlphabet[i]) {
                return (char)(i + 97);
            }
        }
        return ' ';
    }
}
